version: '3.9'

services:
  backend:
    build: ./backend
    container_name: carrental-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/carrental
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kitler@110
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=your-very-secret-key
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: carrental-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://backend:8081
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: carrental-db
    environment:
      MYSQL_ROOT_PASSWORD: Kitler@110
      MYSQL_DATABASE: carrental
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
